import { AggregateRoot } from '@nestjs/cqrs';
import { createObjectIdAsString } from 'src/app/@core/utils/functions/mongo-functions';
import { OrderStatusEnum } from '../constants/enum/order-status-enum'
import { Product } from './product';
import { Invoice } from './invoice';


export class Order extends AggregateRoot {
  public constructor(
    public readonly _id: string,
    public title: string,
    public endDate: Date,
    public deliverDate: Date,
    public type: string,
    public status: string = OrderStatusEnum.PLANING,
    public region?: string,
    public city?: string,
    public address?: string,
    public fileName?: string,
    public fileDescription?: string,
    public fileId?: string,
    public attachmentName?: string,
    public attachmentDescription?: string,
    public attachmentId?: string,
    public attachmentRequired: boolean = false,
    public attachmentDeliverDays?: number,
    public contactInfo?: string,
    public tenderId: string = '',
    public companyId: string = '',
    public userId: string = '',
    public products: Product[] = [] ,
    public Sendedproducts: Product[] = [] ,
    public OrderNr: number = 0,
    public DeliveryMethod: string = '',
    public paymentMethod: string = '',
    public invoices: Invoice[] = [],
    public readonly displayOrder: number = 0,
    public readonly isVisible: boolean = true,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date,
    public readonly deletedAt?: Date,
    public readonly createdBy?: string,
    public readonly updatedBy?: string,
    public readonly deletedBy?: string,
    
  ) {
    super();
  }

  public static create(
    id: string | null,
    title: string,
    endDate: Date,
    deliverDate: Date,
    type: string,
    status: string = OrderStatusEnum.PLANING,
    region: string = null,
    city: string = null,
    address: string = null,
    fileName: string = null,
    fileDescription: string = null,
    fileId: string = null,
    attachmentName: string = null,
    attachmentDescription: string = null,
    attachmentId: string = null,
    attachmentRequired: boolean = false,
    attachmentDeliverDays: number = null,
    contactInfo: string = null,
    tenderId: string = '',
    companyId: string = '',
    userId: string = '',
    products: Product[] = [],
    Sendedproducts: Product[] = [],
    OrderNr: number = 0,
    DeliveryMethod: string = '',
    paymentMethod: string = '',
    invoices:Invoice[]=[],
    displayOrder: number = 0,
    isVisible: boolean = true,
    createdAt: Date = null,
    updatedAt: Date = null,
    deletedAt: Date = null,
    createdBy: string = null,
    updatedBy: string = null,
    deletedBy: string = null,
    
  ): Order {
    return new Order(
      createObjectIdAsString(
        id,
      ),
      title,
      endDate,
      deliverDate,
      type,
      status,
      region,
      city,
      address,
      fileName,
      fileDescription,
      fileId,
      attachmentName,
      attachmentDescription,
      attachmentId,
      attachmentRequired,
      attachmentDeliverDays,
      contactInfo,
      tenderId,
      companyId,
      userId,
      products,
      Sendedproducts,
      OrderNr,
      DeliveryMethod,
      paymentMethod,
      invoices,
      displayOrder,
      isVisible,
      createdAt,
      updatedAt,
      deletedAt,
      createdBy,
      updatedBy,
      deletedBy       
    );
  }
}