import { AggregateRoot } from '@nestjs/cqrs';
import { createObjectIdAsString } from 'src/app/@core/utils/functions/mongo-functions';
import { ItemStatusEnum } from '../constants/enum/item-status-enum';
import { Attachment } from 'src/app/@core/shared/domain/entities/attachment';

export class Item extends AggregateRoot {
  public constructor(
    public readonly _id: string,
    public name: string,
    public SKUCode: string,
    public manufacturer: string,
    public brand: string,
    public model: string,
    public unit: string,
    public categories: string,
    public description: string,
    public price: number,
    public vat: number,
    public stock: number = 0,
    public tags: string[] = [],
    public image: string = '',
    public attachments: Attachment[] = [],
    public status: string = ItemStatusEnum.ACTIVE,
    public type: string,
    public companyId: string,
    public userId: string,
    public ItemNR: number = 0,
    public readonly displayOrder: number = 0,
    public readonly isVisible: boolean = true,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date,
    public readonly deletedAt?: Date,
    public readonly createdBy?: string,
    public readonly updatedBy?: string,
    public readonly deletedBy?: string,
  ) {
    super();
  }

  public static create(
    id: string | null,
    name: string,
    SKUCode: string,
    manufacturer: string,
    brand: string,
    model: string,
    unit: string,
    categories: string,
    description: string,
    price: number,
    vat: number,
    stock: number = 0,
    tags: string[] = [],
    image: string = '',
    attachments: Attachment[] = [],
    status: string = ItemStatusEnum.ACTIVE,
    type: string,
    companyId: string,
    userId: string,    
    ItemNR: number = 0,
    displayOrder: number = 0,
    isVisible: boolean = true,
    createdAt: Date = null,
    updatedAt: Date = null,
    deletedAt: Date = null,
    createdBy: string = null,
    updatedBy: string = null,
    deletedBy: string = null,
  ): Item {
    return new Item(
      createObjectIdAsString(id), // Generate ObjectId if null
      name,
      SKUCode,
      manufacturer,
      brand,
      model,
      unit,
      categories,
      description,
      price,
      vat,
      stock,
      tags,
      image,
      attachments,
      status,
      type,
      companyId,
      userId,      
      ItemNR,
      displayOrder,
      isVisible,
      createdAt,
      updatedAt,
      deletedAt,
      createdBy,
      updatedBy,
      deletedBy,
    );
  }
}
